pid=$1
filename=$2
execution_id=$3
project=$4
caller_class=$5
callee_class=$6


resultDir="results/cling/$project-$caller_class-$callee_class-$execution_id"


## Wait until either the process ends or the process stays inactive for 5 minutes
Timeout=300 # 5 minutes


stopLoop=0
while [ "$stopLoop" -eq 0 ]; do
    # First, sleep and wait for the process to finish
    sleep "$Timeout"
    # Find inactive time
    modifiedTime=$(date -r "logs/cling/$filename" "+%s")
    currentTime=$(date "+%s")
    inActiveTime=$((currentTime-modifiedTime))
    echo "Process $pid is inactive for $inActiveTime seconds"
    if [[ "$inActiveTime" -gt "300" ]]; then
        #Kill process
        kill "$pid"
        echo "killing process $pid"
        #Check if results are available
        if [ -d "$resultDir" ]; then
            echo "Test is generated by cling. id: $execution_id project $project caller class: $caller_class callee class:$callee_class "
        else
            echo "rerun the experiment for cling. id: $execution_id project $project caller class: $caller_class callee class:$callee_class"
            . scripts/run/run_cling.sh $execution_id $project $caller_class $callee_class
        fi
        # This process is killed, so there is no need for the observer. Stop the while loop
        stopLoop=1
    fi
done